name: Terraform Deployment

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  TF_WORKSPACE: ${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
   
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::255945442255:role/github-actions-role
        role-session-name: github-actions-${{ env.TF_WORKSPACE }}
        aws-region: ${{ env.AWS_REGION }}
        
        audience: sts.amazonaws.com

    - uses: hashicorp/setup-terraform@v2
      with:
      terraform_version: 1.11.2  # Pin your version

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  steps:
  - run: terraform init

  - run: terraform plan

  - run: |
      terraform workspace new $TF_WORKSPACE || true
      terraform workspace select $TF_WORKSPACE
      terraform apply -auto-approve